spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nice_bbs
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: nice
mybatis:
  mapper-locations: classpath:com/nice/mapper/*.xml
  type-aliases-package: com.nice.domain
  configuration:
    map-underscore-to-camel-case: true
